### ISSUE TITLE
Plugin not working on typedoc 0.16.9

### ISSUE THREAD

**Issue by alexandercerutti** [mipatterson/typedoc-plugin-markdown-pages#23]
Is this plugin still mantained? I think not.
I'm having this error as output with the following command:

```
npx typedoc src --mdPagesSourcePath .
```

**Error**:

```
Error: The plugin /Users/alexandercerutti/.../node_modules/typedoc-plugin-markdown-pages could not be loaded.

TypeError: declaration_1.OptionDeclaration is not a constructor
    at Object.<anonymous> (/Users/alexandercerutti/.../node_modules/typedoc-plugin-markdown-pages/dist/options.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/alexandercerutti/.../node_modules/typedoc-plugin-markdown-pages/dist/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
Error: Unknown option: --mdPagesSourcePath
Error: Unknown option: --mdPagesSourcePath
```

`OptionDeclaration` is imported from typedoc. I think this has been developed on an older version, because looking at `typedoc/src/lib/utils/options/declaration.ts`, it does not exist.

If someone could update this, maybe via a fork, I'd be very grateful  🙌

**Comment by WilliamJns** [comment]
It's not working at all. @mipatterson is there any solution to make it work again?

**Comment by WilliamJns** [comment]
Any idea to fix this issue?

**Comment by mipatterson** [comment]
@alexandercerutti That is indeed the issue. There have been some changes to TypeDoc that seem to have broken the plugin.

I recently decided to embark on a rewrite of this plugin with goals to:
- Support the latest version of TypeDoc
- Add support for search integration
- Move to a more configuration-based page declaration to support more flexible page titles and ordering
- Add support for inter-page links

I have been developing the plugin against TypeDoc version 0.16.10, but I can test against 0.16.9 as well. I am currently testing the plugin and hope to release it in the next couple of days.

**Comment by alexandercerutti** [comment]
@mipatterson that's great to hear 😄 thank you for the reply!

**Comment by alexandercerutti** [comment]
@mipatterson I'd like to suggest you a thing: since this is a plugin and typedoc will probably still change a lot before reaching v1.0, what about versioning it using the same version of typedoc and write about this in the Readme? So it becomes clear which is the latest supported version of typedoc. 😊 Let me know!

**Comment by mipatterson** [comment]
@alexandercerutti I definitely like the idea of documenting which versions of TypeDoc the plugin is compatible with! I'm getting ready to begin testing the plugin against a few different versions of TypeDoc. The one concern I have with versioning it in lockstep with the TypeDoc library is that breaking changes in the plugin wouldn't be able to conform to semantic versioning rules, which could make consumption difficult for some developers.

**Comment by alexandercerutti** [comment]
Yeah, I was thinking about this. This is the only problem... Actually I don't know how this could be solved. I don't know if semver and npm allow more version numbers (like, `w.x.y.z`) or not. Because if it is like this, you could just shift the version number and reserve the first one to your breaking changes.

**Comment by prashanth2692** [comment]
@alexandercerutti , I am also facing the same issue, can you let me know which versions of typedoc and typedoc-plugin-markdown-pages are compatible. Thanks.

I tried downgrading typedoc version to 0.15.8, but facing runtime exception (Cannot find resource `page.hbs`.).

**Comment by alexandercerutti** [comment]
@prashanth2692 I don't know. I did not test. I'm also waiting for the new version.
Maybe @mipatterson can let you know which might be the problem and the latest compatible version

**Comment by mipatterson** [comment]
@alexandercerutti @prashanth2692 The new plugin can be found here:
[https://github.com/mipatterson/typedoc-plugin-pages](https://github.com/mipatterson/typedoc-plugin-pages)

I think it's an improvement over this original plugin, but it does require more manual configuration.

As for version support, the plugin current supports all versions of TypeDoc since 0.16.5. It might actually support even older versions, but I haven't gotten around to testing those yet.

**Comment by mipatterson** [comment]
I'm closing this issue as this plugin is being deprecated in favor of the [typedoc-plugin-pages](https://github.com/mipatterson/typedoc-plugin-pages) plugin.

**Comment by alexandercerutti** [comment]
A Deprecation notice should be inserted in Readme, IMHO. 😄Anyway, thank you @mipatterson
